---
version: '3.6'

configs:
  log4rs:
    file: log4rs.yaml
  dot-env:
    file: .env

services:
  web-server:
    extends:
      file: docker-compose-base.yml
      service: web-server
    environment:
      - REST_REQUEST_LIMIT_PER_SECOND
      - REST_CONCURRENCY_LIMIT_PER_SERVICE
      - REST_CORS_ALLOWED_ORIGIN

  example:
    extends:
      file: docker-compose-base.yml
      service: example

  ut-coverage:
    extends:
      file: docker-compose-base.yml
      service: ut-coverage

  it-coverage:
    extends:
      file: docker-compose-base.yml
      service: it-coverage
